spring:
  application:
      name: eureak-server

server:
  port: 8761 #启动端口

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${MY_POD_NAME}.${spring.application.name}
    instance-id: ${MY_POD_NAME}.${spring.application.name}:${server.port}
  client:
    registerWithEureka: true  #false:不作为一个客户端注册到注册中心
    fetchRegistry: true      #为true时，可以启动，但报异常：Cannot execute request on any known server
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  server:
    enable-self-preservation: false #关闭保护机制，确保注册中心可以将不可用的实例正确剔除
    eviction-interval-timer-in-ms: 3000
    response-cache-update-interval-ms: 2000