spring:
  application:
    name: eureka-server

server:
  port: 8761 #启动端口

eureka:
  instance:
    prefer-ip-address: ${PREFER_IP_ADDRESS:true}
    hostname: ${EUREKA_INSTANCE_HOST:${spring.application.name}}
    ip-address: ${EUREKA_INSTANCE_IP:${spring.cloud.client.ipAddress}}
    instance-id: ${EUREKA_INSTANCE_IP:${spring.cloud.client.ipAddress}}:${server.port}
  client:
    registerWithEureka: false  #false:不作为一个客户端注册到注册中心
    fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  server:
    enable-self-preservation: false #关闭保护机制，确保注册中心可以将不可用的实例正确剔除
    eviction-interval-timer-in-ms: 3000
    response-cache-update-interval-ms: 2000